/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WatchlistRouteImport } from './routes/watchlist'
import { Route as SubmitRumorRouteImport } from './routes/submit-rumor'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ScoringRouteImport } from './routes/scoring'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LawsRouteImport } from './routes/laws'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as HelpRouteImport } from './routes/help'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DetectRouteImport } from './routes/detect'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmbedIdRouteImport } from './routes/embed.$id'
import { Route as ApiAnalyzeImageRouteImport } from './routes/api/analyze-image'

const WatchlistRoute = WatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmitRumorRoute = SubmitRumorRouteImport.update({
  id: '/submit-rumor',
  path: '/submit-rumor',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoringRoute = ScoringRouteImport.update({
  id: '/scoring',
  path: '/scoring',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LawsRoute = LawsRouteImport.update({
  id: '/laws',
  path: '/laws',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DetectRoute = DetectRouteImport.update({
  id: '/detect',
  path: '/detect',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbedIdRoute = EmbedIdRouteImport.update({
  id: '/embed/$id',
  path: '/embed/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyzeImageRoute = ApiAnalyzeImageRouteImport.update({
  id: '/api/analyze-image',
  path: '/api/analyze-image',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/detect': typeof DetectRoute
  '/docs': typeof DocsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/history': typeof HistoryRoute
  '/laws': typeof LawsRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/scoring': typeof ScoringRoute
  '/signup': typeof SignupRoute
  '/submit-rumor': typeof SubmitRumorRoute
  '/watchlist': typeof WatchlistRoute
  '/api/analyze-image': typeof ApiAnalyzeImageRoute
  '/embed/$id': typeof EmbedIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/detect': typeof DetectRoute
  '/docs': typeof DocsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/history': typeof HistoryRoute
  '/laws': typeof LawsRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/scoring': typeof ScoringRoute
  '/signup': typeof SignupRoute
  '/submit-rumor': typeof SubmitRumorRoute
  '/watchlist': typeof WatchlistRoute
  '/api/analyze-image': typeof ApiAnalyzeImageRoute
  '/embed/$id': typeof EmbedIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/detect': typeof DetectRoute
  '/docs': typeof DocsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/history': typeof HistoryRoute
  '/laws': typeof LawsRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/scoring': typeof ScoringRoute
  '/signup': typeof SignupRoute
  '/submit-rumor': typeof SubmitRumorRoute
  '/watchlist': typeof WatchlistRoute
  '/api/analyze-image': typeof ApiAnalyzeImageRoute
  '/embed/$id': typeof EmbedIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/detect'
    | '/docs'
    | '/forgot-password'
    | '/help'
    | '/history'
    | '/laws'
    | '/login'
    | '/reset-password'
    | '/scoring'
    | '/signup'
    | '/submit-rumor'
    | '/watchlist'
    | '/api/analyze-image'
    | '/embed/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/detect'
    | '/docs'
    | '/forgot-password'
    | '/help'
    | '/history'
    | '/laws'
    | '/login'
    | '/reset-password'
    | '/scoring'
    | '/signup'
    | '/submit-rumor'
    | '/watchlist'
    | '/api/analyze-image'
    | '/embed/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/detect'
    | '/docs'
    | '/forgot-password'
    | '/help'
    | '/history'
    | '/laws'
    | '/login'
    | '/reset-password'
    | '/scoring'
    | '/signup'
    | '/submit-rumor'
    | '/watchlist'
    | '/api/analyze-image'
    | '/embed/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  DashboardRoute: typeof DashboardRoute
  DetectRoute: typeof DetectRoute
  DocsRoute: typeof DocsRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HelpRoute: typeof HelpRoute
  HistoryRoute: typeof HistoryRoute
  LawsRoute: typeof LawsRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ScoringRoute: typeof ScoringRoute
  SignupRoute: typeof SignupRoute
  SubmitRumorRoute: typeof SubmitRumorRoute
  WatchlistRoute: typeof WatchlistRoute
  ApiAnalyzeImageRoute: typeof ApiAnalyzeImageRoute
  EmbedIdRoute: typeof EmbedIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/watchlist': {
      id: '/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof WatchlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submit-rumor': {
      id: '/submit-rumor'
      path: '/submit-rumor'
      fullPath: '/submit-rumor'
      preLoaderRoute: typeof SubmitRumorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scoring': {
      id: '/scoring'
      path: '/scoring'
      fullPath: '/scoring'
      preLoaderRoute: typeof ScoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laws': {
      id: '/laws'
      path: '/laws'
      fullPath: '/laws'
      preLoaderRoute: typeof LawsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/detect': {
      id: '/detect'
      path: '/detect'
      fullPath: '/detect'
      preLoaderRoute: typeof DetectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embed/$id': {
      id: '/embed/$id'
      path: '/embed/$id'
      fullPath: '/embed/$id'
      preLoaderRoute: typeof EmbedIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analyze-image': {
      id: '/api/analyze-image'
      path: '/api/analyze-image'
      fullPath: '/api/analyze-image'
      preLoaderRoute: typeof ApiAnalyzeImageRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  DashboardRoute: DashboardRoute,
  DetectRoute: DetectRoute,
  DocsRoute: DocsRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HelpRoute: HelpRoute,
  HistoryRoute: HistoryRoute,
  LawsRoute: LawsRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ScoringRoute: ScoringRoute,
  SignupRoute: SignupRoute,
  SubmitRumorRoute: SubmitRumorRoute,
  WatchlistRoute: WatchlistRoute,
  ApiAnalyzeImageRoute: ApiAnalyzeImageRoute,
  EmbedIdRoute: EmbedIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
